spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 10
    url: jdbc:postgresql://localhost:5432/patient
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver

  application:
    name: patient-svc

eureka:
  healthcheck:
    enabled: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:9635}}

