server:
  port: ${APP_PORT:8080}

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 10
    url: jdbc:postgresql://${PG_HOST:localhost}:${PG_PORT:5432}/${PG_DB:patient}
    username: ${PG_USER:postgres}
    password: ${PG_PASS}
    driver-class-name: org.postgresql.Driver

  application:
    name: patient-svc

eureka:
  healthcheck:
    enabled: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka}
  instance:
    preferIpAddress: true
    instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}

feign:
  hystrix:
    enabled: true
